# //TODO: update related documentation about jshint options etc.
# //TODO: automate this file
# //for every file in o2.js folder, if the file is not to be excluded
# //jshint the file.

jshint --config jshint-options.json ../o2.js/o2.ajax.core.js
jshint --config jshint-options.json ../o2.js/o2.ajax.extend.js
jshint --config jshint-options.json ../o2.js/o2.ajaxcontroller.core.js
jshint --config jshint-options.json ../o2.js/o2.ajaxstate.core.js
jshint --config jshint-options.json ../o2.js/o2.collection.core.js
jshint --config jshint-options.json ../o2.js/o2.convert.core.js
jshint --config jshint-options.json ../o2.js/o2.cookie.core.js
jshint --config jshint-options.json ../o2.js/o2.core.js
jshint --config jshint-options.json ../o2.js/o2.date.core.js
jshint --config jshint-options.json ../o2.js/o2.debugger.core.js
jshint --config jshint-options.json ../o2.js/o2.dom.class.js
jshint --config jshint-options.json ../o2.js/o2.dom.collide.js
jshint --config jshint-options.json ../o2.js/o2.dom.constants.js
jshint --config jshint-options.json ../o2.js/o2.dom.coordinate.js
jshint --config jshint-options.json ../o2.js/o2.dom.core.js
jshint --config jshint-options.json ../o2.js/o2.dom.dimension.js
jshint --config jshint-options.json ../o2.js/o2.dom.form.js
jshint --config jshint-options.json ../o2.js/o2.dom.load.js
jshint --config jshint-options.json ../o2.js/o2.dom.modify.js
jshint --config jshint-options.json ../o2.js/o2.dom.range.js
jshint --config jshint-options.json ../o2.js/o2.dom.ready.js
jshint --config jshint-options.json ../o2.js/o2.dom.scroll.js
jshint --config jshint-options.json ../o2.js/o2.dom.style.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.child.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.children.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.core.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.ends.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.next.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.nth.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.parent.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.parents.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.prev.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.siblings.js
jshint --config jshint-options.json ../o2.js/o2.dom.traverse.validate.js
jshint --config jshint-options.json ../o2.js/o2.effect.core.js
jshint --config jshint-options.json ../o2.js/o2.event.constants.js
jshint --config jshint-options.json ../o2.js/o2.event.core.js
jshint --config jshint-options.json ../o2.js/o2.event.custom.js
jshint --config jshint-options.json ../o2.js/o2.event.extend.js
jshint --config jshint-options.json ../o2.js/o2.extend.js
jshint --config jshint-options.json ../o2.js/o2.jsonpcontroller.core.js
jshint --config jshint-options.json ../o2.js/o2.jsonp.core.js
jshint --config jshint-options.json ../o2.js/o2.jsonpstate.core.js
jshint --config jshint-options.json ../o2.js/o2.meta.js
jshint --config jshint-options.json ../o2.js/o2.meta.production.js
jshint --config jshint-options.json ../o2.js/o2.method.core.js
jshint --config jshint-options.json ../o2.js/o2.method.event.js
jshint --config jshint-options.json ../o2.js/o2.method.inherit.js
jshint --config jshint-options.json ../o2.js/o2.method.repeat.js
jshint --config jshint-options.json ../o2.js/o2.method.timer.js
jshint --config jshint-options.json ../o2.js/o2.method.transpose.js
jshint --config jshint-options.json ../o2.js/o2.nodejs.footer.js
jshint --config jshint-options.json ../o2.js/o2.nodejs.header.js
jshint --config jshint-options.json ../o2.js/o2.object.core.js
jshint --config jshint-options.json ../o2.js/o2.querystring.core.js
jshint --config jshint-options.json ../o2.js/o2.sortdelegate.core.js
jshint --config jshint-options.json ../o2.js/o2.string.core.js
jshint --config jshint-options.json ../o2.js/o2.string.encode.js
jshint --config jshint-options.json ../o2.js/o2.string.strip.js
jshint --config jshint-options.json ../o2.js/o2.string.transform.js
jshint --config jshint-options.json ../o2.js/o2.supports.core.js
jshint --config jshint-options.json ../o2.js/o2.template.core.js
jshint --config jshint-options.json ../o2.js/o2.timer.core.js
jshint --config jshint-options.json ../o2.js/o2.try.core.js
jshint --config jshint-options.json ../o2.js/o2.unit.core.js
jshint --config jshint-options.json ../o2.js/o2.validation.core.js
jshint --config jshint-options.json ../o2.js/o2.validation.regexp.js
