{
    "bitwise"  : false,
    "curly"    : true,
    "eqeqeq"   : true,
    "forin"    : true,
    "immed"    : true,
    "indent"   : 4,
    "latedef"  : true,
    "newcap"   : true,
    "noarg"    : true,
    "noempty"  : true,
    "nomen"    : true,
    "nonew"    : true,
    "onevar"   : true,
    "plusplus" : false,
    "quotmark" : "single",
    "regexp"   : true,
    "strict"   : true,
    "undef"    : true,
    "unused"   : true,
    "white"    : false,
    "trailing" : true,
    "node"     : true,
    "maxlen"   :80
}
