/*
 *  [ o2.js JavaScript Framework ]( http://o2js.com/ )
 *
 *  This program is distributed under the terms of the "MIT License".
 *  Please see the <LICENSE.md> file for details.
 */

/*
 *   o2.js JavaScrpt Framework Node.JS Module Export
 *
 *  !!! THIS FILE IS AUTOMATICALLY GENERATED      !!!
 *  !!! IF YOU EDIT IT, YOU MAY LOSE YOUR CHANGES !!!
 */

if (!document) {
    var document = {
        getElementsByName      : function() {},
        createElement          : function() {},
        createTextNode         : function() {},
        createDocumentFragment : function() {},
        getElementsByTagName   : function() {},
        styleSheets            : []
    };

    this.document      = document;
    this.setTimeout    = setTimeout;
    this.setInterval   = setInterval;
    this.clearTimeout  = clearTimeout;
    this.clearInterval = clearInterval;
    this.escape        = escape;
    this.navigator     = {
        userAgent : 'o2.js DOM Mockup for Node.JS'
    };
    this.self          = {};
    this.Image         = {};
    this.scrollTo      = function() {};
    this.location      = {};
}

