/*
 * o2.js NodeJS Module Export
 *
 * THIS FILE IS AUTOMATICALLY GENERATED
 * IF YOU EDIT IT, YOU MAY LOSE YOUR CHANGES
 */

if (!document) {
    var document = {
        getElementsByName      : function() {},
        createElement          : function() {},
        createTextNode         : function() {},
        createDocumentFragment : function() {},
        getElementsByTagName   : function() {},
        styleSheets            : []
    };

    this.document      = document;
    this.setTimeout    = setTimeout;
    this.setInterval   = setInterval;
    this.clearTimeout  = clearTimeout;
    this.clearInterval = clearInterval;
    this.escape        = escape;
    this.navigator     = {
        userAgent : 'o2.js DOM Mockup for Node.JS'
    }
    this.self          = {};
    this.Image         = {};
    this.scrollTo      = function() {};
    this.location      = {};
}