/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['timer/core.js']) {
  _$jscoverage['timer/core.js'] = [];
  _$jscoverage['timer/core.js'][1] = 0;
  _$jscoverage['timer/core.js'][3] = 0;
  _$jscoverage['timer/core.js'][4] = 0;
  _$jscoverage['timer/core.js'][7] = 0;
  _$jscoverage['timer/core.js'][11] = 0;
  _$jscoverage['timer/core.js'][16] = 0;
  _$jscoverage['timer/core.js'][17] = 0;
  _$jscoverage['timer/core.js'][20] = 0;
  _$jscoverage['timer/core.js'][21] = 0;
  _$jscoverage['timer/core.js'][23] = 0;
  _$jscoverage['timer/core.js'][25] = 0;
  _$jscoverage['timer/core.js'][27] = 0;
  _$jscoverage['timer/core.js'][30] = 0;
  _$jscoverage['timer/core.js'][31] = 0;
  _$jscoverage['timer/core.js'][32] = 0;
}
_$jscoverage['timer/core.js'][1]++;
"use strict";
_$jscoverage['timer/core.js'][3]++;
if (! window) {
  _$jscoverage['timer/core.js'][4]++;
  throw new Error("o2.timer should run in a browser");
}
_$jscoverage['timer/core.js'][7]++;
var tick = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame || (function (delegate) {
  _$jscoverage['timer/core.js'][11]++;
  return window.setTimeout(delegate, 17);
}), commandQueue = [];
_$jscoverage['timer/core.js'][16]++;
function loop() {
  _$jscoverage['timer/core.js'][17]++;
  tick(loop);
}
_$jscoverage['timer/core.js'][20]++;
exports.initialize = (function () {
  _$jscoverage['timer/core.js'][21]++;
  console.log("tick");
  _$jscoverage['timer/core.js'][23]++;
  loop();
  _$jscoverage['timer/core.js'][25]++;
  if (! commandQueue.length) {
    _$jscoverage['timer/core.js'][25]++;
    return;
  }
  _$jscoverage['timer/core.js'][27]++;
  commandQueue.shift()();
});
_$jscoverage['timer/core.js'][30]++;
exports.delay = (function (delegate, timeout) {
  _$jscoverage['timer/core.js'][31]++;
  return setTimeout((function () {
  _$jscoverage['timer/core.js'][32]++;
  commandQueue.push(delegate);
}), timeout || 0);
});
_$jscoverage['timer/core.js'].source = ["'use strict';","","if (!window) {","    throw new Error('o2.timer should run in a browser');","}","","var tick = window.requestAnimationFrame || window.mozRequestAnimationFrame ||","                window.webkitRequestAnimationFrame ||","                window.msRequestAnimationFrame ||","                function( delegate ) {","                    return window.setTimeout( delegate, 17 );","                },","    commandQueue = [];","","","function loop() {","    tick(loop);","}","","exports.initialize = function() {","    console.log('tick');","","    loop();","","    if (!commandQueue.length) {return;}","","    commandQueue.shift()();","};","","exports.delay = function(delegate, timeout) {","    return setTimeout(function() {","        commandQueue.push(delegate);","    }, timeout || 0);","};"];
