/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['io/core.js']) {
  _$jscoverage['io/core.js'] = [];
  _$jscoverage['io/core.js'][1] = 0;
}
_$jscoverage['io/core.js'][1]++;
"use strict";
_$jscoverage['io/core.js'].source = ["'use strict';","","/**"," * @module o2.io"," */","","/**"," * @class o2.io.core"," */"];
