/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['string/core.js']) {
  _$jscoverage['string/core.js'] = [];
  _$jscoverage['string/core.js'][1] = 0;
  _$jscoverage['string/core.js'][25] = 0;
  _$jscoverage['string/core.js'][26] = 0;
}
_$jscoverage['string/core.js'][1]++;
"use strict";
_$jscoverage['string/core.js'][25]++;
exports.sayHi = (function () {
  _$jscoverage['string/core.js'][26]++;
  return "Hello world; hello stars; hello universe!";
});
_$jscoverage['string/core.js'].source = ["'use strict';","","/**"," * @module o2.string"," */","","/**"," * @submodule o2.string.core"," */","","/**"," * Says hi."," *"," * Usage example:"," *"," *     var ajaxUtil = require('ajax/core');"," *"," *     // `greeting` will be a welcome text of type `String`."," *     var greeting = ajaxUtil.sayHi();"," *"," * @method sayHi"," *"," * @returns {string} \"hi\"."," */","exports.sayHi = function() {","    return 'Hello world; hello stars; hello universe!';","};"];
